spring:
  application:
    name: user-client #le nom de l'application
  profiles:
    active: native
  config:
    import: configserver:http://localhost:8888
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  endpoints:
    web:
      exposure:
        include: "*"



