server:
  port: 8090
  servlet:
    context-path: /restaurant
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  config:
    import:
  application:
    name: restaurant #le nom de l'application
  cloud:
    loadbalancer:
      ribbon:
        enabled: false