spring:
  application:
    name: gateway-client
  profiles:
    active: native
  config:
    import: configserver:http://localhost:8888
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
management:
  endpoints:
    gateway:
      enables: true
    web:
      exposure:
        include: gateway
