server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
<<<<<<< HEAD
          search-locations: file:///C:/Users/Tom/Documents/GitHub/HowLongToEatRepo
=======
<<<<<<< HEAD
          search-locations: file:///D:\cours fac\M1 TNSID\S8\How long to eat - git config repo #à modifier selon le pc utilisé
=======
          search-locations: file:///C:\Users\Tom\Documents\GitHub\HowLongToEatRepo
>>>>>>> 807a56492c30f79a4a018d4faf7972d1a9a0e31f
>>>>>>> 6fdd086d54e1d6860ea09c6a982b17e7b3ef3a28
  profiles:
    active: native