server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\cours fac\M1 TNSID\S8\How long to eat - git config repo
  profiles:
    active: native