server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\Thomas\Documents\Cours M1\S2\NTR\How long to eat - git config repo #à modifier selon le pc utilisé
  profiles:
    active: native